title: Kevin Ramlal
logo: /circle-cropped.png
description: Market Making + Market Microstructure + Python
show_downloads: true
google_analytics:
markdown: kramdown
theme: jekyll-theme-minimal
roadmaplogo: /road1.png
qbooklogo: /qblogo1.JPG
about: /aboutme.md
