title: Kevin Ramlal
logo: /92507994_1458761130969955_2416489870793900032_n.jpg
description: Kevin
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true
